---
apiVersion: v1
kind: Secret
metadata:
  name: grandstream-snmp-secret
  namespace: grandstream-monitoring
type: Opaque
stringData:
  # for SNMP v2c
  SNMP_COMMUNITY: public
  # for SNMP v3
  SNMP_USERNAME: myuser
  SNMP_AUTH_PASSPHRASE: myauthpass
  SNMP_PRIV_PASSPHRASE: myprivpass
