{
 "title": "Grandstream Device Monitor",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(grandstream_exporter_up, device_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grandstream_host_resources_mib_hrsystemuptime{device_ip=\"$target\"}"
    }
   ]
  },
  {
   "title": "CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "grandstream_host_resources_mib_hrprocessorload{device_ip=\"$target\"}",
     "legendFormat": "Core {{hrProcessorIndex}}"
    }
   ]
  },
  {
   "title": "Storage & Memory Usage (Megabytes)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "grandstream_storage_used_megabytes{device_ip=\"$target\"}",
     "legendFormat": "{{descr}} (Used)"
    },
    {
     "expr": "grandstream_storage_total_megabytes{device_ip=\"$target\"}",
     "legendFormat": "{{descr}} (Total)"
    }
   ]
  }
 ]
}